// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1pd1f6xv-lK2nhxg-5DS2Qft9wAYrmLQ',
    appId: '1:639915832863:web:4f2de8e5ee4ea06be4c72a',
    messagingSenderId: '639915832863',
    projectId: 'pattyventas-3bad6',
    authDomain: 'pattyventas-3bad6.firebaseapp.com',
    storageBucket: 'pattyventas-3bad6.appspot.com',
    measurementId: 'G-LRK2GEWQJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoBOQoNq00ip1RbudF78OjBWd54iq4w_E',
    appId: '1:639915832863:android:749bf6211c603206e4c72a',
    messagingSenderId: '639915832863',
    projectId: 'pattyventas-3bad6',
    storageBucket: 'pattyventas-3bad6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUUL7exGkhO55GeaNt5zAzFzO3h6H4828',
    appId: '1:639915832863:ios:884c1d3c265a8e3ee4c72a',
    messagingSenderId: '639915832863',
    projectId: 'pattyventas-3bad6',
    storageBucket: 'pattyventas-3bad6.appspot.com',
    iosClientId: '639915832863-nitl327efbs9ku1n6ijpuhjvlas4o706.apps.googleusercontent.com',
    iosBundleId: 'com.example.pattyventas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUUL7exGkhO55GeaNt5zAzFzO3h6H4828',
    appId: '1:639915832863:ios:33c4f56fe2079fd9e4c72a',
    messagingSenderId: '639915832863',
    projectId: 'pattyventas-3bad6',
    storageBucket: 'pattyventas-3bad6.appspot.com',
    iosClientId: '639915832863-ffk649ijvsab8gc1upjreium7pdgm1d6.apps.googleusercontent.com',
    iosBundleId: 'com.example.pattyventas.RunnerTests',
  );
}
